# -*- coding: utf-8 -*-
"""deep_learning_optimizers_SGD_NAG_EMWA.ipynb.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1afm8MswW9bY7Q0T6SWKnpvMR-vA76KDU
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.get_dataset_names()

df=sns.load_dataset("dots")

df.info()

df.head()

for i in df.columns:
  print(df[i].unique())
  print("="*30)

df.describe()

df=pd.get_dummies(df,columns=["align","choice"],drop_first=True)

df=df.astype(float)

df.head(12)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Flatten,Dropout,BatchNormalization
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import optimizers
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score,accuracy_score,confusion_matrix,mean_squared_error,classification_report

x=df.drop(columns=["align_sacc"])
y=df["align_sacc"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=2)

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.transform(x_test)

model=Sequential()
model.add(Dense(4,activation="relu",input_dim=4))
# model.add(BatchNormalization())
model.add(Dense(4,activation="relu"))
# model.add(BatchNormalization())
model.add(Dense(1,activation="sigmoid"))

optimzar=optimizers.SGD(
    learning_rate=0.01,
    momentum=0.5,
    nesterov=True
)

callback=EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True,
    verbose=1

)

model.compile(loss="binary_crossentropy",optimizer=optimzar,metrics=["accuracy"])

history=model.fit(x_train_scaled,y_train,epochs=50,validation_split=0.2,batch_size=2,callbacks=callback)

x_train_scaled.shape

model.get_weights()[0]

pred=model.predict(x_test_scaled)

pred_y=(pred>0.5).astype(int)

accuracy_score(y_test,pred_y)

cm=confusion_matrix(y_test,pred_y)

plt.figure(figsize=(6,3))
sns.heatmap(cm,annot=True)
plt.show()

classification_report(y_test,pred_y)

plt.plot(history.history["loss"])
plt.plot(history.history["val_loss"])

plt.plot(history.history["accuracy"])
plt.plot(history.history["val_accuracy"])

